name: build kernel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: mrproper
      working-directory: ./linux
      run: make mrproper
    - name: clean
      working-directory: ./linux
      run: make clean
    - name: allmodconfig
      working-directory: ./linux
      run: make allmodconfig
    - name: greponlymods
      working-directory: ./linux
      run: cat .config | grep "=m" > allmodconfig
    - name: writeconfig 
      working-directory: ./linux
      run: mv allmodconfig .config
    - name: update apt sources
      working-directory: ./linux
      run: sudo apt-get update
    - name: install generic kernel
      working-directory: ./linux
      run: sudo apt-get install -y linux-image-generic libelf-dev
    - name: defaultconfigoptions
      working-directory: ./linux
      run: ls /boot/config-* | head -n 1 | xargs -i cat {} | | grep -v "CONFIG_SYSTEM_TRUSTED_KEYS" | grep -v "CONFIG_SYSTEM_REVOCATION_KEYS" | grep -v "=m" | grep -v "#" | grep "." >> .config
    - name: olddefconfig
      working-directory: ./linux
      run: make olddefconfig
    - name: makeall
      working-directory: ./linux
      run: make all
